name: compilation test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install software
      run: sudo apt-get update; sudo apt-get install gfortran libopenmpi-dev libfftw3-dev
    - name: test compilation
      run: |
        cd src/
        make && make run
        make OMP+=-fopenmp OTH+=-DIMPDIFF && make run
